name: BrowserStack CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  browserstack-test:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run BrowserStack Tests
        run: npm test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: browserstack-report
          path: mochawesome-report/
          retention-days: 7

  deploy:
    needs: browserstack-test
    runs-on: ubuntu-latest

    steps:
      - name: Deployment Step
        run: echo "Deploying application..."